/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_graphic_TextureLoader */

#ifndef _Included_com_example_graphic_TextureLoader
#define _Included_com_example_graphic_TextureLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_graphic_TextureLoader
 * Method:    texImage2DNonPremultipliedAlpha
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_example_graphic_TextureLoader_texImage2DNonPremultipliedAlpha
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
